inherit_from: .rubocop_todo.yml

require:
  rubocop-rails

AllCops:
  Exclude:
    - 'app/assets/**/*'
    - 'bin/**'
    - 'config/**'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'gems/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/UselessAssignment:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/InverseOf:
 Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false