version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "4306:3306" #左がホストマシンで利用したいポート番号、右がコンテナ内のポート番号

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/medical_log
    ports:
      - "3000:3000"
    tty: true #ポート待受などをしていないコンテナを起動させ続けるオプション
    stdin_open: true #標準入力出来るようになるオプション
    depends_on:
      - db
