version: 2.1
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: コンテナの起動を待つ
          command: sleep 100
      - run:
          name: DBのセットアップ
          command: docker-compose run web bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: webpackerをインストール
          command: docker-compose run web bundle exec rails webpacker:install
      - run:
          name: webpackerをコンパイル
          command: docker-compose run web bundle exec rails webpacker:compile
      - run:
          name: RSpecテスト実行
          command: docker-compose run web bundle exec rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down