version: 2.1
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    docker:
      image: circleci/ruby:2.5.3-node-browsers
      environment:
        - BUNDLER_VERSION: 2.0.2
        - RAILS_ENV: 'test'
      image: circleci/mysql:5.7
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '127.0.0.1'
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: コンテナの起動を待つ
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: データベースのセットアップ
          command: docker-compose run web bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          command: docker-compose run web bundle exec rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down