---
platform: linux
image_resource:
  type: docker-image
  source: {repository: rubyfog/fog-google}
inputs:
- name: fog-google-src
  path: src/fog-google
run:
  path: src/fog-google/ci/tasks/run-int.sh
params:
  rake_task: replace-me
  google_project: replace-me
  google_client_email: replace-me
  google_json_key_data: |
    replace-me